package io.github.shivam61.loadshedder.core;
public enum DecisionReason { CAPACITY_EXCEEDED, RATE_LIMITED, QUEUE_FULL, CONTROLLER_REJECTION, PRIORITY_SHED, DEADLINE_EXCEEDED, HARD_LIMIT_BREACHED, HEALTHY }
